Dtspo 8117 plum prod
hmcts/azure-platform-terraform pull request #1238
Opened 2022-08-16 12:39 UTC by ciaranca

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSPO-8117

### Change description ###

Adds plum to to prod frontdoor and adds whitelisting IP's

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (sbox-frontendappgateway)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-sbox-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"sbox-frontendappgateway","Vars":{}} -->

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (sbox-shutter)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"sbox-shutter","Vars":{}} -->

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (sbox-global)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"sbox-global","Vars":{}} -->

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (ptl-dynatrace_activegate)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"ptl-dynatrace_activegate","Vars":{}} -->

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (sbox-cftapps_private_dns)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"sbox-cftapps_private_dns","Vars":{}} -->

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (sbox-apim)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"sbox-apim","Vars":{}} -->

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (sbox-apim-appgw)




<pre><code>Plan: 1 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be created
  + resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
      + id                         = (known after apply)
      + log_analytics_workspace_id = "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/oms-automation/providers/Microsoft.OperationalInsights/workspaces/hmcts-sandbox"
      + name                       = "AppGw"
      + target_resource_id         = "/subscriptions/ea3a8c1e-af9d-4108-bc86-a7e2d267f49c/resourceGroups/hmcts-hub-sbox-int/providers/Microsoft.Network/applicationGateways/cft-apim00-sandbox-agw"

      + metric {
          + category = "AllMetrics"
          + enabled  = true

          + retention_policy {
              + enabled = true
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"sbox-apim-appgw","Vars":{}} -->

2022-08-16 12:41 UTC, hmcts-platform-operations commented
## Plan Result (sbox-backendappgateway)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"sbox-backendappgateway","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (demo-cftapps_cluster_lb_backend)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/aks00-demo-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/aks01-demo-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"demo-cftapps_cluster_lb_backend","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (ithc-backendappgateway)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

  # module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[1] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks01-ithc-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"ithc-backendappgateway","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (demo-cftapps_private_dns)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"demo-cftapps_private_dns","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (test-cftapps_private_dns)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"test-cftapps_private_dns","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (ithc-cftapps_private_dns)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"ithc-cftapps_private_dns","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (test-apim)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"test-apim","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (demo-apim)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"demo-apim","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (stg-cftapps_private_dns)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"stg-cftapps_private_dns","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (test-backendappgateway)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

  # module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[1] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks01-perftest-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"test-backendappgateway","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (stg-cftapps_cluster_lb_backend)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/aks00-aat-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/aks01-aat-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"stg-cftapps_cluster_lb_backend","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (stg-apim)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"stg-apim","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (ithc-apim)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"ithc-apim","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (ithc-frontendappgateway)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"ithc-frontendappgateway","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (demo-global)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"demo-global","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (stg-cftapps_cluster_lb)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.cftapps-frontend-cluster-lb.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.cftapps-frontend-cluster-lb.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-aat-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"stg-cftapps_cluster_lb","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (dev-global)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"dev-global","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (test-cftapps_cluster_lb)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.cftapps-frontend-cluster-lb.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.cftapps-frontend-cluster-lb.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-perftest-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"test-cftapps_cluster_lb","Vars":{}} -->

2022-08-16 12:43 UTC, hmcts-platform-operations commented
## Plan Result (test-cftapps_cluster_lb_backend)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/aks00-perftest-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/aks01-perftest-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"test-cftapps_cluster_lb_backend","Vars":{}} -->

2022-08-16 12:44 UTC, hmcts-platform-operations commented
## Plan Result (ithc-global)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"ithc-global","Vars":{}} -->

2022-08-16 12:44 UTC, hmcts-platform-operations commented
## Plan Result (test-global)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"test-global","Vars":{}} -->

2022-08-16 12:44 UTC, hmcts-platform-operations commented
## Plan Result (test-frontendappgateway)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"test-frontendappgateway","Vars":{}} -->

2022-08-16 12:44 UTC, hmcts-platform-operations commented
## Plan Result (stg-global)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"stg-global","Vars":{}} -->

2022-08-16 13:54 UTC, hmcts-platform-operations commented
## Plan Result (prod-cftapps_cluster_lb)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.cftapps-frontend-cluster-lb.azurerm_application_gateway.ag[0]
  * module.cftapps-frontend-cluster-lb.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.cftapps-frontend-cluster-lb.data.azurerm_monitor_diagnostic_categories.diagnostic_categories[0] will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_monitor_diagnostic_categories" "diagnostic_categories" {
      + id          = (known after apply)
      + logs        = (known after apply)
      + metrics     = (known after apply)
      + resource_id = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw"

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.cftapps-frontend-cluster-lb.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw"
        name                = "aks-fe-00-prod-agw"
        tags                = {
            "application"  = "core"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "High"
            "environment"  = "production"
        }
        # (4 unchanged attributes hidden)


      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/div-dn"
          ~ name         = "div-dn" -> "plum"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/div-da"
          ~ name         = "div-da" -> "div-dn"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/div-rfe"
          ~ name         = "div-rfe" -> "div-da"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/div-pfe"
          ~ name         = "div-pfe" -> "div-rfe"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/div-amend"
          ~ name         = "div-amend" -> "div-pfe"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/nfdiv-civil-partnership"
          ~ name         = "nfdiv-civil-partnership" -> "div-amend"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/sscs-tribunals"
          ~ name         = "sscs-tribunals" -> "nfdiv-civil-partnership"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/sscs-tya"
          ~ name         = "sscs-tya" -> "sscs-tribunals"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/sscs-cor"
          ~ name         = "sscs-cor" -> "sscs-tya"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/xui-webapp"
          ~ name         = "xui-webapp" -> "sscs-cor"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/xui-manage-org"
          ~ name         = "xui-manage-org" -> "xui-webapp"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/xui-approve-org"
          ~ name         = "xui-approve-org" -> "xui-manage-org"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/xui-register-org"
          ~ name         = "xui-register-org" -> "xui-approve-org"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/cmc"
          ~ name         = "cmc" -> "xui-register-org"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/cmc-legal"
          ~ name         = "cmc-legal" -> "cmc"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/gateway-ccd"
          ~ name         = "gateway-ccd" -> "cmc-legal"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/return-case-doc-ccd"
          ~ name         = "return-case-doc-ccd" -> "gateway-ccd"
            # (2 unchanged attributes hidden)
        }
      ~ backend_address_pool {
            id           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks-fe-00-prod-agw/backendAddressPools/probate"
           [...]

2022-08-16 13:54 UTC, hmcts-platform-operations commented
## Plan Result (prod-cftapps_cluster_lb_backend)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks00-prod-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[1] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                         = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/aks-infra-prod-rg/providers/Microsoft.Network/applicationGateways/aks01-prod-agw|AppGw"
        name                       = "AppGw"
        # (2 unchanged attributes hidden)

      - log {
          - category = "ApplicationGatewayAccessLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayFirewallLog" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }
      - log {
          - category = "ApplicationGatewayPerformanceLog" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"prod-cftapps_cluster_lb_backend","Vars":{}} -->

2022-08-16 13:54 UTC, hmcts-platform-operations commented
## Plan Result (prod-cftapps_private_dns)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"prod-cftapps_private_dns","Vars":{}} -->

2022-08-16 13:56 UTC, hmcts-platform-operations commented
## Plan Result (prod-global)




<pre><code>Plan: 2 to add, 2 to change, 0 to destroy.</code></pre>

* Create
  * module.landing_zone.azurerm_frontdoor_custom_https_configuration.https[&#34;plum&#34;]
  * module.landing_zone.azurerm_frontdoor_firewall_policy.custom[&#34;plum&#34;]
* Update
  * module.landing_zone.azurerm_frontdoor.main
  * module.landing_zone.azurerm_monitor_diagnostic_setting.frontdoor_diagnostics




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.landing_zone.data.azurerm_monitor_diagnostic_categories.diagnostic_categories will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_monitor_diagnostic_categories" "diagnostic_categories" {
      + id          = (known after apply)
      + logs        = (known after apply)
      + metrics     = (known after apply)
      + resource_id = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod"

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.landing_zone.azurerm_frontdoor.main will be updated in-place
  ~ resource "azurerm_frontdoor" "main" {
        id                                           = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod"
        name                                         = "hmcts-prod"
        tags                                         = {
            "application"  = "core"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "High"
            "environment"  = "production"
        }
        # (14 unchanged attributes hidden)

      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-div-dn" -> "healthProbeSettings-plum"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/div-dn"
          ~ load_balancing_name = "loadBalancingSettings-div-dn" -> "loadBalancingSettings-plum"
          ~ name                = "div-dn" -> "plum"

          ~ backend {
              ~ host_header = "www.decree-nisi.apply-divorce.service.gov.uk" -> "plum.platform.hmcts.net"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-div-da" -> "healthProbeSettings-div-dn"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/div-da"
          ~ load_balancing_name = "loadBalancingSettings-div-da" -> "loadBalancingSettings-div-dn"
          ~ name                = "div-da" -> "div-dn"

          ~ backend {
              ~ host_header = "www.decree-absolute.apply-divorce.service.gov.uk" -> "www.decree-nisi.apply-divorce.service.gov.uk"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-div-rfe" -> "healthProbeSettings-div-da"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/div-rfe"
          ~ load_balancing_name = "loadBalancingSettings-div-rfe" -> "loadBalancingSettings-div-da"
          ~ name                = "div-rfe" -> "div-da"

          ~ backend {
              ~ host_header = "www.respond-divorce.service.gov.uk" -> "www.decree-absolute.apply-divorce.service.gov.uk"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-div-pfe" -> "healthProbeSettings-div-rfe"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/div-pfe"
          ~ load_balancing_name = "loadBalancingSettings-div-pfe" -> "loadBalancingSettings-div-rfe"
          ~ name                = "div-pfe" -> "div-rfe"

          ~ backend {
              ~ host_header = "www.apply-divorce.service.gov.uk" -> "www.respond-divorce.service.gov.uk"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-div-amend" -> "healthProbeSettings-div-pfe"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/div-amend"
          ~ load_balancing_name = "loadBalancingSettings-div-amend" -> "loadBalancingSettings-div-pfe"
          ~ name                = "div-amend" -> "div-pfe"

          ~ backend {
              ~ host_header = "www.manage-application.apply-divorce.service.gov.uk" -> "www.apply-divorce.service.gov.uk"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-nfdiv-civil-partnership" -> "healthProbeSettings-div-amend"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/nfdiv-civil-partnership"
          ~ load_balancing_name = "loadBalancingSettings-nfdiv-civil-partnership" -> "loadBalancingSettings-div-amend"
          ~ name                = "nfdiv-civil-partnership" -> "div-amend"

          ~ backend {
              ~ host_header = "www.end-civil-partnership.service.gov.uk" -> "www.manage-application.apply-divorce.service.gov.uk"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-sscs-tribunals" -> "healthProbeSettings-nfdiv-civil-partnership"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/sscs-tribunals"
          ~ load_balancing_name = "loadBalancingSettings-sscs-tribunals" -> "loadBalancingSettings-nfdiv-civil-partnership"
          ~ name                = "sscs-tribunals" -> "nfdiv-civil-partnership"

          ~ backend {
              ~ host_header = "www.appeal-benefit-decision.service.gov.uk" -> "www.end-civil-partnership.service.gov.uk"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-sscs-tya" -> "healthProbeSettings-sscs-tribunals"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/sscs-tya"
          ~ load_balancing_name = "loadBalancingSettings-sscs-tya" -> "loadBalancingSettings-sscs-tribunals"
          ~ name                = "sscs-tya" -> "sscs-tribunals"

          ~ backend {
              ~ host_header = "www.track-benefit-appeal.service.gov.uk" -> "www.appeal-benefit-decision.service.gov.uk"
                # (6 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "healthProbeSettings-sscs-cor" -> "healthProbeSettings-sscs-tya"
            id                  = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Network/frontDoors/hmcts-prod/backendPools/sscs-cor"
          ~ load_balancing_name = "loadBalancingSettings-sscs-cor" -> "loadBalancingSettings-sscs-tya"
          ~ name                = "sscs-cor" -> "sscs-tya"

          ~ backend {
              ~ host_header = "www.manage.appeal-benefit-decision.service.gov.uk" -> "www.track-benefit-appeal.service.gov.uk"
          [...]

2022-08-16 13:56 UTC, hmcts-platform-operations commented
## Plan Result (prod-apim)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":1238,"Program":"tfcmt","SHA1":"","Target":"prod-apim","Vars":{}} -->

2022-08-18 08:29 UTC, thomast1906 commented on environments/prod/prod.tfvars
> +    global_exclusions = [
Are all the exclusions needed?

2022-08-18 09:14 UTC, ciaranca commented on environments/prod/prod.tfvars
> +    global_exclusions = [
Have removed exclusions

2022-08-18 12:10 UTC, thomast1906 requested changes
Please check failures in the CI

2022-09-01 09:48 UTC, hmcts-platform-operations commented
## Plan Result (prod-shutter)




<pre><code>Plan: 40 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * module.shutter.azurerm_cdn_endpoint.shutter_endpoint[&#34;plum&#34;]
  * module.shutter.azurerm_cdn_profile.main[&#34;cnp&#34;]
  * module.shutter.azurerm_storage_account.shutter_store[&#34;plum&#34;]
  * module.shutter.azurerm_template_deployment.custom_domain[&#34;cft-api-mgmt&#34;]
  * module.shutter.azurerm_template_deployment.custom_domain[&#34;plum&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;adoption&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;cft-api-mgmt&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;cmc&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;cmc-legal&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;div-amend&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;div-da&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;div-dn&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;div-pfe&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;div-rfe&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;fact&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;fact-admin&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;fees-register&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;gateway-ccd&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;hmi-apim&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;ia-aip&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;idam-user-dashboard&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;idam-web-admin&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;idam-web-public&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;lau&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;manage-payments&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;nfdiv-civil-partnership&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;paybubble&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;payment-outcome&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;pcq&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;plum&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;probate&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;reformscan&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;return-case-doc-ccd&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;sscs-cor&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;sscs-tribunals&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;sscs-tya&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;xui-approve-org&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;xui-manage-org&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;xui-register-org&#34;]
  * module.shutter.null_resource.enable_custom_https_cmd[&#34;xui-webapp&#34;]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.shutter.azurerm_cdn_endpoint.shutter_endpoint["plum"] will be created
  + resource "azurerm_cdn_endpoint" "shutter_endpoint" {
      + content_types_to_compress     = (known after apply)
      + fqdn                          = (known after apply)
      + id                            = (known after apply)
      + is_compression_enabled        = false
      + is_http_allowed               = false
      + is_https_allowed              = true
      + location                      = "westus"
      + name                          = "hmcts-plum-shutter-prod"
      + origin_host_header            = (known after apply)
      + origin_path                   = (known after apply)
      + probe_path                    = (known after apply)
      + profile_name                  = "hmcts-shutter-cnp"
      + querystring_caching_behaviour = "IgnoreQueryString"
      + resource_group_name           = "shutter-app-prod-rg"
      + tags                          = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/azure-platform-terraform"
          + "businessArea" = "CFT"
          + "criticality"  = "High"
          + "environment"  = "production"
        }

      + origin {
          + host_name  = (known after apply)
          + http_port  = 80
          + https_port = 443
          + name       = (known after apply)
        }
    }

  # module.shutter.azurerm_cdn_profile.main["cnp"] will be created
  + resource "azurerm_cdn_profile" "main" {
      + id                  = (known after apply)
      + location            = "westus"
      + name                = "hmcts-shutter-cnp"
      + resource_group_name = "shutter-app-prod-rg"
      + sku                 = "Standard_Verizon"
      + tags                = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/azure-platform-terraform"
          + "businessArea" = "CFT"
          + "criticality"  = "High"
          + "environment"  = "production"
        }
    }

  # module.shutter.azurerm_storage_account.shutter_store["plum"] will be created
  + resource "azurerm_storage_account" "shutter_store" {
      + access_tier                       = (known after apply)
      + account_kind                      = "StorageV2"
      + account_replication_type          = "RAGRS"
      + account_tier                      = "Standard"
      + allow_nested_items_to_be_public   = false
      + cross_tenant_replication_enabled  = false
      + enable_https_traffic_only         = true
      + id                                = (known after apply)
      + infrastructure_encryption_enabled = false
      + is_hns_enabled                    = false
      + large_file_share_enabled          = (known after apply)
      + location                          = "uksouth"
      + min_tls_version                   = "TLS1_0"
      + name                              = "hmctsplumshutterprod"
      + nfsv3_enabled                     = false
      + primary_access_key                = (sensitive value)
      + primary_blob_connection_string    = (sensitive value)
      + primary_blob_endpoint             = (known after apply)
      + primary_blob_host                 = (known after apply)
      + primary_connection_string         = (sensitive value)
      + primary_dfs_endpoint              = (known after apply)
      + primary_dfs_host                  = (known after apply)
      + primary_file_endpoint             = (known after apply)
      + primary_file_host                 = (known after apply)
      + primary_location                  = (known after apply)
      + primary_queue_endpoint            = (known after apply)
      + primary_queue_host                = (known after apply)
      + primary_table_endpoint            = (known after apply)
      + primary_table_host                = (known after apply)
      + primary_web_endpoint              = (known after apply)
      + primary_web_host                  = (known after apply)
      + queue_encryption_key_type         = "Service"
      + resource_group_name               = "shutter-app-prod-rg"
      + secondary_access_key              = (sensitive value)
      + secondary_blob_connection_string  = (sensitive value)
      + secondary_blob_endpoint           = (known after apply)
      + secondary_blob_host               = (known after apply)
      + secondary_connection_string       = (sensitive value)
      + secondary_dfs_endpoint            = (known after apply)
      + secondary_dfs_host                = (known after apply)
      + secondary_file_endpoint           = (known after apply)
      + secondary_file_host               = (known after apply)
      + secondary_ [...]

2022-09-01 09:53 UTC, thomast1906 approved these changes

2022-09-01 12:51 UTC, merged