Update main.tf
hmcts/azure-platform-terraform pull request #2338
Opened 2024-12-11 14:38 UTC by Tyler-35

### Jira link
[DTSPO-22820](https://tools.hmcts.net/jira/browse/DTSPO-22820)

### Change description

Testing to see if current application gateways remind unchanged with WAF settings

2024-12-11 14:42 UTC, hmcts-platform-operations commented
## Plan Result (sbox_apim - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"sbox_apim - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:42 UTC, hmcts-platform-operations commented
## Plan Result (sbox_global - TerraformPlanApply)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostics_access_logs_sa" {
        id                             = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/lz-sbox-rg/providers/Microsoft.Cdn/profiles/hmcts-sbox|fd-log-analytics-logs-sa"
        name                           = "fd-log-analytics-logs-sa"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"sbox_global - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:42 UTC, hmcts-platform-operations commented
## Plan Result (sbox_private_dns - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"sbox_private_dns - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:42 UTC, hmcts-platform-operations commented
## Plan Result (sbox_shutter_webapp - TerraformPlanApply)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.static_webapp.azurerm_dns_txt_record.zone_validate[&#34;labs-goldenpath-ashleigh&#34;]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.static_webapp.azurerm_dns_txt_record.zone_validate["labs-goldenpath-ashleigh"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "zone_validate" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformMgmtRG/providers/Microsoft.Network/dnsZones/sandbox.platform.hmcts.net/TXT/_dnsauth.labs-goldenpath-ashleigh"
        name                = "_dnsauth.labs-goldenpath-ashleigh"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





## :warning: Errors

* add a label sbox_shutter_webapp - TerraformPlanApply/add-or-update: POST https://api.github.com/repos/hmcts/azure-platform-terraform/issues/2338/labels: 422 Validation Failed [{Resource:Label Field:name Code:invalid Message:}]
<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"sbox_shutter_webapp - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:42 UTC, hmcts-platform-operations commented
## Plan Result (sbox_apim_appgw - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_application_gateway.ag[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.data.azurerm_monitor_diagnostic_categories.diagnostic_categories will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_monitor_diagnostic_categories" "diagnostic_categories" {
      + id                  = (known after apply)
      + log_category_groups = (known after apply)
      + log_category_types  = (known after apply)
      + logs                = (known after apply)
      + metrics             = (known after apply)
      + resource_id         = "/subscriptions/ea3a8c1e-af9d-4108-bc86-a7e2d267f49c/resourceGroups/hmcts-hub-sbox-int/providers/Microsoft.Network/applicationGateways/cft-apim00-sandbox-agw"
    }

  # module.app-gw.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/ea3a8c1e-af9d-4108-bc86-a7e2d267f49c/resourceGroups/hmcts-hub-sbox-int/providers/Microsoft.Network/applicationGateways/cft-apim00-sandbox-agw"
        name                              = "cft-apim00-sandbox-agw"
        tags                              = {
            "application"  = "core"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Low"
            "environment"  = "sandbox"
            "expiresAfter" = "3000-01-01"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "cft-api-mgmt-appgw.sandbox.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/ea3a8c1e-af9d-4108-bc86-a7e2d267f49c/resourceGroups/hmcts-hub-sbox-int/providers/Microsoft.Network/applicationGateways/cft-apim00-sandbox-agw/probes/cft-api-mgmt-appgw-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "cft-api-mgmt-appgw-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      + probe {
          + host                                      = "cft-api-mgmt-appgw.sandbox.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 10
          + minimum_servers                           = 0
          + name                                      = "cft-api-mgmt-appgw-probe"
          + path                                      = "/status-0123456789abcdef"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                                   = 15
          + unhealthy_threshold                       = 3
        }

        # (15 unchanged blocks hidden)
    }

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                             = "/subscriptions/ea3a8c1e-af9d-4108-bc86-a7e2d267f49c/resourceGroups/hmcts-hub-sbox-int/providers/Microsoft.Network/applicationGateways/cft-apim00-sandbox-agw|AppGw"
        name                           = "AppGw"
        # (5 unchanged attributes hidden)

      ~ metric (known after apply)
      - metric {
          - category = "AllMetrics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"sbox_apim_appgw - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:42 UTC, hmcts-platform-operations commented
## Plan Result (sbox_backendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.backendappgateway.azurerm_application_gateway.ag[0]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.backendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw"
        name                              = "cft-aks00-sandbox-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Low"
            "environment"  = "sandbox"
            "expiresAfter" = "3000-01-01"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "bulk-scan-orchestrator-sandbox.service.core-compute-sandbox.internal" -> null
          - id                                        = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw/probes/bulk-scan-orchestrator" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bulk-scan-orchestrator" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bulk-scan-payment-processor-sandbox.service.core-compute-sandbox.internal" -> null
          - id                                        = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw/probes/bulk-scan-payment-processor" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bulk-scan-payment-processor" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bulk-scan-processor-sandbox.service.core-compute-sandbox.internal" -> null
          - id                                        = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw/probes/bulk-scan-processor" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bulk-scan-processor" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bulk-scan-sample-app-sandbox.service.core-compute-sandbox.internal" -> null
          - id                                        = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw/probes/bulk-scan-sample-app" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bulk-scan-sample-app" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "div-emca-sandbox.service.core-compute-sandbox.internal" -> null
          - id                                        = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw/probes/div-emca" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "div-emca" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "docmosis.sandbox.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/resourceGroups/cft-sbox-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-sandbox-agw/probes/dg-docmosis" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "dg-docmosis" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_ [...]

2024-12-11 14:43 UTC, hmcts-platform-operations commented
## Plan Result (demo_apim - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"demo_apim - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:43 UTC, hmcts-platform-operations commented
## Plan Result (stg_apim - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"stg_apim - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:43 UTC, hmcts-platform-operations commented
## Plan Result (ithc_apim - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"ithc_apim - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:43 UTC, hmcts-platform-operations commented
## Plan Result (stg_apim_appgw - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_application_gateway.ag[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.data.azurerm_monitor_diagnostic_categories.diagnostic_categories will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_monitor_diagnostic_categories" "diagnostic_categories" {
      + id                  = (known after apply)
      + log_category_groups = (known after apply)
      + log_category_types  = (known after apply)
      + logs                = (known after apply)
      + metrics             = (known after apply)
      + resource_id         = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-aat-agw"
    }

  # module.app-gw.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-aat-agw"
        name                              = "cft-apim00-aat-agw"
        tags                              = {
            "application"  = "core"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "High"
            "environment"  = "staging"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.aat.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-aat-agw/probes/cft-mtls-api-mgmt-appgw-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "cft-mtls-api-mgmt-appgw-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      + probe {
          + host                                      = "cft-mtls-api-mgmt-appgw.aat.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 10
          + minimum_servers                           = 0
          + name                                      = "cft-mtls-api-mgmt-appgw-probe"
          + path                                      = "/status-0123456789abcdef"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                                   = 15
          + unhealthy_threshold                       = 3
        }

        # (20 unchanged blocks hidden)
    }

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                             = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-aat-agw|AppGw"
        name                           = "AppGw"
        # (5 unchanged attributes hidden)

      ~ metric (known after apply)
      - metric {
          - category = "AllMetrics" -> null
          - enabled  = true -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = true -> null
            }
        }

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"stg_apim_appgw - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:43 UTC, hmcts-platform-operations commented
## Plan Result (ithc_private_dns - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"ithc_private_dns - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:43 UTC, hmcts-platform-operations commented
## Plan Result (prod_private_dns - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"prod_private_dns - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (stg_private_dns - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"stg_private_dns - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (ithc_global - TerraformPlanApply)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostics_access_logs_sa" {
        id                             = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/lz-ithc-rg/providers/Microsoft.Cdn/profiles/hmcts-ithc|fd-log-analytics-logs-sa"
        name                           = "fd-log-analytics-logs-sa"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"ithc_global - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (test_apim - TerraformPlanApply)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"test_apim - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (test_apim_appgw - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_application_gateway.ag[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.data.azurerm_monitor_diagnostic_categories.diagnostic_categories will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_monitor_diagnostic_categories" "diagnostic_categories" {
      + id                  = (known after apply)
      + log_category_groups = (known after apply)
      + log_category_types  = (known after apply)
      + logs                = (known after apply)
      + metrics             = (known after apply)
      + resource_id         = "/subscriptions/fb084706-583f-4c9a-bdab-949aac66ba5c/resourceGroups/hmcts-hub-nonprodi/providers/Microsoft.Network/applicationGateways/cft-apim00-perftest-agw"
    }

  # module.app-gw.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/fb084706-583f-4c9a-bdab-949aac66ba5c/resourceGroups/hmcts-hub-nonprodi/providers/Microsoft.Network/applicationGateways/cft-apim00-perftest-agw"
        name                              = "cft-apim00-perftest-agw"
        tags                              = {
            "application"  = "core"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "testing"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/fb084706-583f-4c9a-bdab-949aac66ba5c/resourceGroups/hmcts-hub-nonprodi/providers/Microsoft.Network/applicationGateways/cft-apim00-perftest-agw/probes/cft-mtls-api-mgmt-appgw-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "cft-mtls-api-mgmt-appgw-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/fb084706-583f-4c9a-bdab-949aac66ba5c/resourceGroups/hmcts-hub-nonprodi/providers/Microsoft.Network/applicationGateways/cft-apim00-perftest-agw/probes/civil-sdt-commissioning-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "civil-sdt-commissioning-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/fb084706-583f-4c9a-bdab-949aac66ba5c/resourceGroups/hmcts-hub-nonprodi/providers/Microsoft.Network/applicationGateways/cft-apim00-perftest-agw/probes/civil-sdt-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "civil-sdt-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      + probe {
          + host                                      = "cft-mtls-api-mgmt-appgw.perftest.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 10
          + minimum_servers                           = 0
          + name                                      = "cft-mtls-api-mgmt-appgw-probe"
          + path                                      = "/status-0123456789abcdef"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                                   = 15
          + unhealthy_threshold                       = 3
        }
      + probe {
          + host                                      = "cft-mtls-api-mgmt-appgw.perftest.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 10
          + minimum_servers                           = 0
          + name                                      = "civil-sdt-commissioning-probe"
          + path                                      = "/status-0123456789abcdef"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                                   = 15
          + unhealthy_threshold                       = 3
        }
      + probe {
          + host                                      = "cft-mtls-api-mgmt-appgw.perftest.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 10
          + minimum_servers                           = 0
          + name                                      = "civil-sdt-probe"
          + path                                      = "/status-0123456789abcdef"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                                   = 15
          + unhealthy_threshold                       = 3
        }

        # (36 unchanged blocks hidden)
    }

  # module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                             = "/subscriptions/fb084706-583f-4c9a-bdab-949aac66ba5c/resourceGroups/hm [...]

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (perftest_global - TerraformPlanApply)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostics_access_logs_sa" {
        id                             = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/lz-perftest-rg/providers/Microsoft.Cdn/profiles/hmcts-perftest|fd-log-analytics-logs-sa"
        name                           = "fd-log-analytics-logs-sa"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"perftest_global - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (test_frontendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_application_gateway.ag[0]
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw"
        name                              = "cft-aks-fe-00-perftest-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "testing"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "administer-orgs.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw/probes/xui-approve-org" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "xui-approve-org" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "adoption-web.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw/probes/adoption-web" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "adoption-web" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw/probes/bar" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "benefit-appeal.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw/probes/sscs-tribunals" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "sscs-tribunals" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-api-mgmt.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw/probes/cft-api-mgmt" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "cft-api-mgmt" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "civil-citizen-ui.perftest.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-perftest-agw/probes/civil-citizen-ui" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "civil-citizen-ui" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                   [...]

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (prod_shutter_webapp - TerraformPlanApply)




<pre><code>Plan: 0 to add, 6 to change, 0 to destroy.</code></pre>

* Update
  * module.static_webapp.azurerm_dns_txt_record.zone_validate[&#34;adoption&#34;]
  * module.static_webapp.azurerm_dns_txt_record.zone_validate[&#34;cui-ra&#34;]
  * module.static_webapp.azurerm_dns_txt_record.zone_validate[&#34;et-staff-pet&#34;]
  * module.static_webapp.azurerm_dns_txt_record.zone_validate[&#34;et-syr&#34;]
  * module.static_webapp.azurerm_dns_txt_record.zone_validate[&#34;private-law&#34;]
  * module.static_webapp.azurerm_dns_txt_record.zone_validate[&#34;sscs-ibca&#34;]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.static_webapp.azurerm_dns_txt_record.zone_validate["adoption"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "zone_validate" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformMgmtRG/providers/Microsoft.Network/dnsZones/platform.hmcts.net/TXT/_dnsauth.apply-for-adoption"
        name                = "_dnsauth.apply-for-adoption"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

  # module.static_webapp.azurerm_dns_txt_record.zone_validate["cui-ra"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "zone_validate" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformMgmtRG/providers/Microsoft.Network/dnsZones/manage-your-support-for-hmcts-services.service.gov.uk/TXT/_dnsauth"
        name                = "_dnsauth"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

  # module.static_webapp.azurerm_dns_txt_record.zone_validate["et-staff-pet"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "zone_validate" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformMgmtRG/providers/Microsoft.Network/dnsZones/employmenttribunals.service.gov.uk/TXT/_dnsauth.admin"
        name                = "_dnsauth.admin"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

  # module.static_webapp.azurerm_dns_txt_record.zone_validate["et-syr"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "zone_validate" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformMgmtRG/providers/Microsoft.Network/dnsZones/respond-employment-tribunals.service.gov.uk/TXT/_dnsauth.www"
        name                = "_dnsauth.www"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

  # module.static_webapp.azurerm_dns_txt_record.zone_validate["private-law"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "zone_validate" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformMgmtRG/providers/Microsoft.Network/dnsZones/apply-to-court-about-child-arrangements-c100.service.gov.uk/TXT/_dnsauth.www"
        name                = "_dnsauth.www"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

  # module.static_webapp.azurerm_dns_txt_record.zone_validate["sscs-ibca"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "zone_validate" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformMgmtRG/providers/Microsoft.Network/dnsZones/appeal-infected-blood-compensation-decision.service.gov.uk/TXT/_dnsauth"
        name                = "_dnsauth"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + record {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }

Plan: 0 to add, 6 to change, 0 to destroy.
```

</details>





## :warning: Errors

* add a label prod_shutter_webapp - TerraformPlanApply/add-or-update: POST https://api.github.com/repos/hmcts/azure-platform-terraform/issues/2338/labels: 422 Validation Failed [{Resource:Label Field:name Code:invalid Message:}]
<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"prod_shutter_webapp - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (prod_global - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.premium_front_door.azurerm_dns_txt_record.public_dns_record[&#34;adoption&#34;]
  * module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.premium_front_door.azurerm_dns_txt_record.public_dns_record["adoption"] will be updated in-place
  ~ resource "azurerm_dns_txt_record" "public_dns_record" {
        id                  = "/subscriptions/ed302caf-ec27-4c64-a05e-85731c3ce90e/resourceGroups/reformmgmtrg/providers/Microsoft.Network/dnsZones/platform.hmcts.net/TXT/_dnsauth.apply-for-adoption"
        name                = "_dnsauth.apply-for-adoption"
        tags                = {}
        # (4 unchanged attributes hidden)

      - record {
          - value = "n3zyn06dl4jk9flktv4d018rxhrrjfm7" -> null
        }
      + record {
          + value = "_9ozmnw86sdvw3w8hbmgpg3htq6rdavz"
        }
    }

  # module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostics_access_logs_sa" {
        id                             = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/lz-prod-rg/providers/Microsoft.Cdn/profiles/hmcts-prod|fd-log-analytics-logs-sa"
        name                           = "fd-log-analytics-logs-sa"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"prod_global - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (stg_frontendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_application_gateway.ag[0]
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-aat-agw"
        name                              = "cft-aks-fe-00-aat-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "High"
            "environment"  = "staging"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "administer-orgs.aat.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-aat-agw/probes/xui-approve-org" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "xui-approve-org" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "adoption-web.aat.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-aat-agw/probes/adoption-web" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "adoption-web" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "adoption.aat.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-aat-agw/probes/adoption" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "adoption" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar.aat.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-aat-agw/probes/bar" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "benefit-appeal.aat.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-aat-agw/probes/sscs-tribunals" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "sscs-tribunals" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-api-mgmt.aat.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/cft-aat-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-aat-agw/probes/cft-api-mgmt" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "cft-api-mgmt" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                  [...]

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (prod_apim_appgw - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.app-gw.azurerm_application_gateway.ag[0]
  * module.app-gw.azurerm_monitor_diagnostic_setting.diagnostic_settings[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.app-gw.data.azurerm_monitor_diagnostic_categories.diagnostic_categories will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_monitor_diagnostic_categories" "diagnostic_categories" {
      + id                  = (known after apply)
      + log_category_groups = (known after apply)
      + log_category_types  = (known after apply)
      + logs                = (known after apply)
      + metrics             = (known after apply)
      + resource_id         = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-prod-agw"
    }

  # module.app-gw.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-prod-agw"
        name                              = "cft-apim00-prod-agw"
        tags                              = {
            "application"  = "core"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "High"
            "environment"  = "production"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-prod-agw/probes/cft-mtls-api-mgmt-appgw-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "cft-mtls-api-mgmt-appgw-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-prod-agw/probes/civil-sdt-commissioning-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "civil-sdt-commissioning-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-prod-agw/probes/civil-sdt-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "civil-sdt-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-mtls-api-mgmt-appgw.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/0978315c-75fe-4ada-9d11-1eb5e0e0b214/resourceGroups/hmcts-hub-prod-int/providers/Microsoft.Network/applicationGateways/cft-apim00-prod-agw/probes/civil-sdt-test-probe" -> null
          - interval                                  = 10 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "civil-sdt-test-probe" -> null
          - path                                      = "/status-0123456789abcdef" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      + probe {
          + host                                      = "cft-mtls-api-mgmt-appgw.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 10
          + minimum_servers                           = 0
          + name                                      = "cft-mtls-api-mgmt-appgw-probe"
          + path                                      = "/status-0123456789abcdef"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                                   = 15
          + unhealthy_threshold                       = 3
        }
      + probe {
          + host                                      = "cft-mtls-api-mgmt-appgw.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 10
          + minimum_servers                           = 0
          + name                                      = "civil-sdt-commissioning-probe"
          + path                                      = "/status-0123456789abcdef"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                               [...]

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (demo_global - TerraformPlanApply)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostics_access_logs_sa" {
        id                             = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/lz-demo-rg/providers/Microsoft.Cdn/profiles/hmcts-demo|fd-log-analytics-logs-sa"
        name                           = "fd-log-analytics-logs-sa"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"demo_global - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (aat_global - TerraformPlanApply)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.premium_front_door.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostics_access_logs_sa" {
        id                             = "/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/resourceGroups/lz-aat-rg/providers/Microsoft.Cdn/profiles/hmcts-aat|fd-log-analytics-logs-sa"
        name                           = "fd-log-analytics-logs-sa"
        # (6 unchanged attributes hidden)

      - metric {
          - category = "AllMetrics" -> null
          - enabled  = false -> null

          - retention_policy {
              - days    = 0 -> null
              - enabled = false -> null
            }
        }

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":2338,"Program":"tfcmt","SHA1":"","Target":"aat_global - TerraformPlanApply","Vars":{}} -->

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (prod_frontendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_application_gateway.ag[0]
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-prod-agw"
        name                              = "cft-aks-fe-00-prod-agw"
        tags                              = {
            "application"  = "core"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "High"
            "environment"  = "production"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "admin.employmenttribunals.service.gov.uk" -> null
          - id                                        = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-prod-agw/probes/et-staff-pet" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "et-staff-pet" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "admin.find-court-tribunal.service.gov.uk" -> null
          - id                                        = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-prod-agw/probes/fact-admin" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "fact-admin" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "administer-orgs.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-prod-agw/probes/xui-approve-org" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "xui-approve-org" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "appeal-infected-blood-compensation-decision.service.gov.uk" -> null
          - id                                        = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-prod-agw/probes/sscs-ibca" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "sscs-ibca" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "appeal-tax-tribunal.service.gov.uk" -> null
          - id                                        = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-prod-agw/probes/tt-pet" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "tt-pet" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "apply-for-adoption.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/resourceGroups/cft-prod-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-prod-agw/probes/adoption" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "adoption" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold  [...]

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (demo_frontendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_application_gateway.ag[0]
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-demo-agw"
        name                              = "cft-aks-fe-00-demo-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "demo"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "ac-int-gateway-ccd.demo.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-demo-agw/probes/ac-int-gateway-ccd" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "ac-int-gateway-ccd" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "administer-orgs-int.demo.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-demo-agw/probes/xui-approve-org-int" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "xui-approve-org-int" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "administer-orgs.demo.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-demo-agw/probes/xui-approve-org" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "xui-approve-org" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "adoption-web.demo.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-demo-agw/probes/adoption-web" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "adoption-web" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar-int.demo.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-demo-agw/probes/bar-int" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar-int" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar.demo.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-demo-agw/probes/bar" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> nu [...]

2024-12-11 14:44 UTC, hmcts-platform-operations commented
## Plan Result (ithc_frontendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 2 to change, 0 to destroy.</code></pre>

* Update
  * module.frontendappgateway.azurerm_application_gateway.ag[0]
  * module.frontendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.frontendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw"
        name                              = "cft-aks-fe-00-ithc-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "ithc"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "administer-orgs.ithc.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw/probes/xui-approve-org" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "xui-approve-org" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "adoption-web.ithc.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw/probes/adoption-web" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "adoption-web" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar.ithc.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw/probes/bar" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "benefit-appeal.ithc.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw/probes/sscs-tribunals" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "sscs-tribunals" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "cft-api-mgmt.ithc.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw/probes/cft-api-mgmt" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "cft-api-mgmt" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "civil-citizen-ui.ithc.platform.hmcts.net" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks-fe-00-ithc-agw/probes/civil-citizen-ui" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "civil-citizen-ui" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
    [...]

2024-12-11 14:45 UTC, hmcts-platform-operations commented
## Plan Result (demo_backendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 4 to change, 0 to destroy.</code></pre>

* Update
  * module.backendappgateway.azurerm_application_gateway.ag[0]
  * module.backendappgateway.azurerm_application_gateway.ag[1]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.backendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-demo-agw"
        name                              = "cft-aks00-demo-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "demo"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "aac-manage-case-assignment-demo.service.core-compute-demo.internal" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-demo-agw/probes/aac-manage-case-assignment" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "aac-manage-case-assignment" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-judicial-booking-service-demo.service.core-compute-demo.internal" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-demo-agw/probes/am-judicial-booking-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-judicial-booking-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-org-role-mapping-service-demo.service.core-compute-demo.internal" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-demo-agw/probes/am-org-role-mapping-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-org-role-mapping-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-role-assignment-service-demo.service.core-compute-demo.internal" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-demo-agw/probes/am-role-assignment-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-role-assignment-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar-api-demo.service.core-compute-demo.internal" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-demo-agw/probes/bar-api" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar-api" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bulk-scan-orchestrator-demo.service.core-compute-demo.internal" -> null
          - id                                        = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-demo-agw/probes/bulk-scan-orchestrator" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                            [...]

2024-12-11 14:45 UTC, hmcts-platform-operations commented
## Plan Result (test_backendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 4 to change, 0 to destroy.</code></pre>

* Update
  * module.backendappgateway.azurerm_application_gateway.ag[0]
  * module.backendappgateway.azurerm_application_gateway.ag[1]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.backendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw"
        name                              = "cft-aks00-perftest-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "testing"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "aac-manage-case-assignment-perftest.service.core-compute-perftest.internal" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw/probes/aac-manage-case-assignment" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "aac-manage-case-assignment" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-judicial-booking-service-perftest.service.core-compute-perftest.internal" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw/probes/am-judicial-booking-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-judicial-booking-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-org-role-mapping-service-perftest.service.core-compute-perftest.internal" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw/probes/am-org-role-mapping-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-org-role-mapping-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-role-assignment-service-perftest.service.core-compute-perftest.internal" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw/probes/am-role-assignment-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-role-assignment-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar-api-perftest.service.core-compute-perftest.internal" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw/probes/bar-api" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar-api" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bulk-scan-orchestrator-perftest.service.core-compute-perftest.internal" -> null
          - id                                        = "/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/resourceGroups/cft-perftest-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-perftest-agw/probes/bulk-scan-orchestrator" -> null
          - interval                                  = 20 -> nul [...]

2024-12-11 14:45 UTC, hmcts-platform-operations commented
## Plan Result (ithc_backendappgateway - TerraformPlanApply)




<pre><code>Plan: 0 to add, 4 to change, 0 to destroy.</code></pre>

* Update
  * module.backendappgateway.azurerm_application_gateway.ag[0]
  * module.backendappgateway.azurerm_application_gateway.ag[1]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]
  * module.backendappgateway.azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[1]




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.backendappgateway.azurerm_application_gateway.ag[0] will be updated in-place
  ~ resource "azurerm_application_gateway" "ag" {
        id                                = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw"
        name                              = "cft-aks00-ithc-agw"
        tags                              = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/azure-platform-terraform"
            "businessArea" = "CFT"
            "criticality"  = "Medium"
            "environment"  = "ithc"
            "startupMode"  = "always"
        }
        # (8 unchanged attributes hidden)

      - probe {
          - host                                      = "aac-manage-case-assignment-ithc.service.core-compute-ithc.internal" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw/probes/aac-manage-case-assignment" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "aac-manage-case-assignment" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "adoption-cos-api-ithc.service.core-compute-ithc.internal" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw/probes/adoption-cos-api" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "adoption-cos-api" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-org-role-mapping-service-ithc.service.core-compute-ithc.internal" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw/probes/am-org-role-mapping-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-org-role-mapping-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "am-role-assignment-service-ithc.service.core-compute-ithc.internal" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw/probes/am-role-assignment-service" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "am-role-assignment-service" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "bar-api-ithc.service.core-compute-ithc.internal" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw/probes/bar-api" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "bar-api" -> null
          - path                                      = "/health/liveness" -> null
          - pick_host_name_from_backend_http_settings = false -> null
          - port                                      = 0 -> null
          - protocol                                  = "Http" -> null
          - timeout                                   = 15 -> null
          - unhealthy_threshold                       = 3 -> null

          - match {
              - status_code = [
                  - "200-399",
                ] -> null
                # (1 unchanged attribute hidden)
            }
        }
      - probe {
          - host                                      = "camunda-api-ithc.service.core-compute-ithc.internal" -> null
          - id                                        = "/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/resourceGroups/cft-ithc-network-rg/providers/Microsoft.Network/applicationGateways/cft-aks00-ithc-agw/probes/camunda-api" -> null
          - interval                                  = 20 -> null
          - minimum_servers                           = 0 -> null
          - name                                      = "camunda-api" -> null
          - path     [...]

2024-12-13 15:56 UTC, thomast1906 commented on components/frontendappgateway/main.tf
> +module "frontendappgateway_waf_enabled" {
can you give more meaningful name? this is for `pubsub` services

2024-12-13 15:58 UTC, thomast1906 requested changes
This is a seperate component in theory, can you create as similar to likes of https://github.com/hmcts/azure-platform-terraform/tree/cc9d687ffeb51c1e3ac4cfb13703aca42f7d7991/components/apim-appgw

2025-01-07 09:57 UTC, hmcts-platform-operations commented
## Plan Result (demo_pubsubappgateway - TerraformPlanApply)




<pre><code>Plan: 5 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * module.pubsubappgateway[0].azurerm_application_gateway.ag[0]
  * module.pubsubappgateway[0].azurerm_monitor_diagnostic_setting.diagnostic_settings[0]
  * module.pubsubappgateway[0].azurerm_monitor_diagnostic_setting.diagnostics_access_logs_sa[0]
  * module.pubsubappgateway[0].azurerm_public_ip.app_gw[0]
  * module.pubsubappgateway[0].azurerm_web_application_firewall_policy.waf_policy




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.pubsubappgateway[0].azurerm_application_gateway.ag[0] will be created
  + resource "azurerm_application_gateway" "ag" {
      + firewall_policy_id          = (known after apply)
      + id                          = (known after apply)
      + location                    = "uksouth"
      + name                        = "cft-fe-00-demo-agw-pubsub"
      + private_endpoint_connection = (known after apply)
      + resource_group_name         = "cft-demo-network-rg"
      + tags                        = {
          + "application"  = "core"
          + "autoShutdown" = "true"
          + "builtFrom"    = "hmcts/azure-platform-terraform"
          + "businessArea" = "CFT"
          + "criticality"  = "Medium"
          + "environment"  = "demo"
          + "startupMode"  = "always"
        }
      + zones                       = [
          + "1",
          + "2",
          + "3",
        ]

      + autoscale_configuration {
          + max_capacity = 10
          + min_capacity = 2
        }

      + backend_address_pool {
          + fqdns        = []
          + id           = (known after apply)
          + ip_addresses = [
              + "10.50.79.221",
              + "10.50.95.221",
            ]
          + name         = "em-icp"
        }

      + backend_http_settings {
          + cookie_based_affinity               = "Disabled"
          + id                                  = (known after apply)
          + name                                = "em-icp"
          + pick_host_name_from_backend_address = false
          + port                                = 80
          + probe_id                            = (known after apply)
          + probe_name                          = "em-icp"
          + protocol                            = "Http"
          + request_timeout                     = 30
          + trusted_root_certificate_names      = []
            # (3 unchanged attributes hidden)
        }

      + frontend_ip_configuration {
          + id                            = (known after apply)
          + name                          = "appGwPublicFrontendIp"
          + private_ip_address            = (known after apply)
          + private_ip_address_allocation = "Dynamic"
          + private_link_configuration_id = (known after apply)
          + public_ip_address_id          = (known after apply)
        }
      + frontend_ip_configuration {
          + id                            = (known after apply)
          + name                          = "appGwPrivateFrontendIp"
          + private_ip_address            = "10.50.98.8"
          + private_ip_address_allocation = "Static"
          + private_link_configuration_id = (known after apply)
          + subnet_id                     = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/virtualNetworks/cft-demo-vnet/subnets/aks-appgw"
        }

      + frontend_port {
          + id   = (known after apply)
          + name = "http"
          + port = 80
        }

      + gateway_ip_configuration {
          + id        = (known after apply)
          + name      = "gateway"
          + subnet_id = "/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/resourceGroups/cft-demo-network-rg/providers/Microsoft.Network/virtualNetworks/cft-demo-vnet/subnets/aks-appgw"
        }

      + http_listener {
          + frontend_ip_configuration_id   = (known after apply)
          + frontend_ip_configuration_name = "appGwPrivateFrontendIp"
          + frontend_port_id               = (known after apply)
          + frontend_port_name             = "http"
          + host_name                      = "em-icp.demo.platform.hmcts.net"
          + host_names                     = []
          + id                             = (known after apply)
          + name                           = "em-icp"
          + protocol                       = "Http"
          + ssl_certificate_id             = (known after apply)
          + ssl_profile_id                 = (known after apply)
            # (3 unchanged attributes hidden)
        }

      + probe {
          + host                                      = "em-icp.demo.platform.hmcts.net"
          + id                                        = (known after apply)
          + interval                                  = 20
          + minimum_servers                           = 0
          + name                                      = "em-icp"
          + path                                      = "/health/liveness"
          + pick_host_name_from_backend_http_settings = false
          + protocol                                  = "Http"
          + timeout                                   = 15
          + unhealthy_threshold                       = 3
        }

      + request_routing_rule {
          + backend_address_pool_id     = (known after apply)
          + backend_address_pool_name   = "em-icp"
          + backend_http_settings_id    = (known after apply)
          + backend_http_settings_name  = "em-icp"
          + http_listener_id            = (known after apply)
          + http_listener_name          = "em-icp"
          + id                          = (known after apply)
          + name                        = "em-icp"
          + priority                    = 10
          + redirect_configuration_id   = (known after apply)
          + rewrite_rule_set_id         = (known after apply)
          + rewrite_rule_set_name       = "x_fwded_proto"
          + rule_type                   = "Basic"
          + url_path_map_id             = (known after apply)
            # (2 unchanged attributes hidden)
        }

      + rewrite_rule_set {
          + id   = (known after apply)
          + name = "x_fwded_proto"

          + rewrite_rule {
              + name          = "x_fwded_proto"
              + rule_sequence = 100

              + request_header_configuration {
                  + header_name  = "X-Forwarded-Proto"
                  + header_value = "https"
                }
              + request_header_configuration {
                  + header_name  = "X-Forwarded-Port"
                  + header_value = "443"
                }
              + request_header_configuration {
                  + header_name  = "X-Forwarded-For"
                  + header_value = "{var_add_x_forwarded_for_proxy}"
                }
            }
        }

      + sku {
          + name = "WAF_v2"
          + tier = "WAF_v2"
        }

      + ssl_policy (known after apply)
    }

  # module.pubsubappgateway[0].azurerm_monitor_diagnostic_setting.diagnostic_settings[0] will be created
  + resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
      + id                             = (known after apply)
      + log_analytics_destination_type = (known after apply)
      + log_analytics_workspace_id     = "/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/resourceGroups/oms-automation/providers/Microsoft.OperationalInsights/workspaces/hmcts-nonprod"
      + name                           = "app-gw"
      + target_resource_id             = (known after apply)

      + enabled_log (known after apply)

      + log (known after apply)

      + metric {
          + category = "AllMetrics"
          + enabled  = true
        }
    }

  # module.pubsubappgateway[0].azurerm_mo [...]

2025-01-09 16:20 UTC, endakelly approved these changes

2025-01-09 16:59 UTC, merged